### ISSUE TITLE
Make the command globally installable

### ISSUE THREAD

**Issue by gausby** [gausby/scaffold#4]
The command should be installable with `mix archive.install`

**Comment by gausby** [comment]
I've tried to make the command installable via

``` shell
$ MIX_ENV=prod mix archive.build
$ mix archive.install
```

Which works, but when executing the command it will complain that ConfigParser (a dependency) cannot be found:

``` shell
$ mix scaffold my_project
** (UndefinedFunctionError) undefined function: ConfigParser.parse_file/1 (module ConfigParser is not available)
    ConfigParser.parse_file("/Users/martin/.gitconfig")
    lib/tasks/scaffold.ex:61: Mix.Tasks.Scaffold.get_git_config!/0
    lib/tasks/scaffold.ex:23: Mix.Tasks.Scaffold.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

I don't know if it is Scaffold that has been set up incorrectly, or if the problem is with the ConfigParser module. I have to ask some people much wiser than I.

**Comment by gausby** [comment]
Dependencies are not carried over, so I will need to inline the dependencies.
